version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm start ## comando a executar
    ports: 
      - "8888:8888" ## redirecionamento de porta quando chegar alguma requisição na porta 8888 chama o container na porta 8888
    volumes: 
      - .:/usr/app ## monitora a pasta atual . e envia as alterações para a pasta /usr/app
      